test('Hello World', () => {

})

test('Failed test!', () => {
    throw new Error('Failure!')
})